version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: issue_parser
      MYSQL_USER: megastos
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql


  rabbit:
    image: rabbitmq:3.7.5
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: mypass

  celery-beat:
    build: .
    links:
      - rabbit
    environment:
      PYTHONUNBUFFERED: 1
      RABBIT_USERNAME: "admin"
      RABBIT_PASSWORD: "mypass"
      RABBIT_HOST: "rabbit"
      SECRET: "de()5w1g2y-*4417f2x@em@g5d)i0@ae7w7!ay4n1dn6&1_@ge"
    command: celery beat -A issue_parser  -l warning

  celery-worker:
    build: .
    links:
      - rabbit
    environment:
      PYTHONUNBUFFERED: 1
      RABBIT_USERNAME: "admin"
      RABBIT_PASSWORD: "mypass"
      RABBIT_HOST: "rabbit"
      DB_USER: "megastos"
      DB_PASSWORD: "root"
      DB_ENGINE: django.db.backends.mysql
      DB_TABLE: issue_parser
      DB_HOST: db
      DB_PORT: 3306
      SECRET: "de()5w1g2y-*4417f2x@em@g5d)i0@ae7w7!ay4n1dn6&1_@ge"
    command: celery worker -A issue_parser -l warning

  nginx:
    image: nginx:1-alpine
    ports:
      - "8000:80"
    volumes:
      - static:/code/static:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web:web
  web:
    build: .
    command: "sh -c config/dev-docker-entrypoint.sh"
    environment:
      PYTHONUNBUFFERED: 1
      DEBUG: "True"
      RABBIT_USERNAME: "admin"
      RABBIT_PASSWORD: "mypass"
      RABBIT_HOST: "rabbit"
      DB_USER: "megastos"
      DB_PASSWORD: "root"
      DB_ENGINE: django.db.backends.mysql
      DB_TABLE: issue_parser
      DB_HOST: db
      DB_PORT: 3306
      SECRET: "de()5w1g2y-*4417f2x@em@g5d)i0@ae7w7!ay4n1dn6&1_@ge"
    volumes:
      - static:/code/static
      - .:/code/
    links:
     - db:db

volumes:
    static:
