version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: issue_parser
      MYSQL_USER: megastos
      MYSQL_PASSWORD: root
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    volumes:
     - .:/code
    links:
     - db:db
